name: CentOS7

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/ubuntu.yml'
  pull_request:
#    branches: [ main ]
    paths-ignore:
      - '**.md'
    workflow_dispatch:

env:
#  MAKEFLAGS: -j4
  CACHE_VER: 3
  DEPS: deps
  V_BOOST: '1.74.0'
  V_BOOST_: 1_74_0
  V_OPENSSL: '1.1.1k'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: centos:7
    strategy:
      fail-fast: false
    steps:
      - name: Install packages
        run: |
          yum -y update
          yum -y remove git
          yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
          yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          yum -y update
          yum -y install epel-release 
          yum -y install double-conversion-devel jemalloc-devel glog-devel gflags-devel snappy-devel                    \
                         libevent-devel libsodium-devel gperf libzstd-devel xmlto xz-devel bzip2-devel python3 wget     \
                         bison flex cmake3 lz4-devel sudo git postgresql-devel binutils-devel autoconf automake libtool \
                         libuuid-devel libatomic libcurl-devel perl-core pcre-devel pkgconfig
          yum clean all

      - name: Configure cmake
        run: |
          echo #! /bin/sh > /usr/local/bin/cmake
          echo cmake3 \"\$@\" > /usr/local/bin/cmake
          chmod +x /usr/local/bin/cmake

      - name: Install devtoolset-9
        run: |
          yum install centos-release-scl -y
          yum clean all
          yum install devtoolset-9-* -y
          scl enable devtoolset-9 -- gcc --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create deps folder
        run: |
          mkdir ${{ env.DEPS }}
          mkdir bootstrap

      - name: Process cache
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.DEPS }}
            bootstrap
          key:  centos7-v${{ env.CACHE_VER }}

      - name: Load boost
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          cd bootstrap
          wget https://boostorg.jfrog.io/artifactory/main/release/${{ env.V_BOOST }}/source/boost_${{ env.V_BOOST_ }}.tar.gz -nv -O boost.tar.gz
          tar -xzf boost.tar.gz
          cd boost_${{ env.V_BOOST_ }}
          scl enable devtoolset-9 -- ./bootstrap.sh

      - name: Install boost
        run: |
          cd bootstrap/boost_${{ env.V_BOOST_ }}
          scl enable devtoolset-9 -- ./b2 -d1 --with-context --with-filesystem --with-program_options --with-regex  \
                                                             --with-system --with-thread --with-date_time           \
                                                             --with-iostreams --prefix=/usr/local install    

      - name: Load OpenSSL 1.1.1
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          cd bootstrap
          wget https://ftp.openssl.org/source/openssl-${V_OPENSSL}.tar.gz -nv -O openssl.tar.gz
          tar -xzf openssl.tar.gz
          cd openssl-${V_OPENSSL}
          scl enable devtoolset-9 -- ./config --prefix=/usr/local --libdir=lib  --openssldir=/etc/ssl no-shared zlib-dynamic

      - name: Install OpenSSL 1.1.1
        run: |
          cd bootstrap/openssl-${V_OPENSSL}
          make
          make install

      - name: Configure
        run: |
          mkdir build
          cd build
          scl enable devtoolset-9 -- cmake3 ..

      - name: Build
        run: |
          cd build
          scl enable devtoolset-9 -- make 
