name: Ubuntu

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/centos7.yml'
  pull_request:
#    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  MAKEFLAGS: -j4
  CACHE_VER: 8
  DEPS: deps

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
          bison flex libcap-dev libevent-dev libiberty-dev libnuma-dev libsnappy-dev  \
          libsodium-dev libtool m4 make pkg-config unzip gperf libboost-all-dev       \
          libdouble-conversion-dev libgflags-dev libgoogle-glog-dev libjemalloc-dev   \
          binutils-dev libkrb5-dev liblz4-dev liblzma-dev libsasl2-dev libssl-dev     \
          libzstd-dev zlib1g-dev wget cmake autoconf automake libcurl4-openssl-dev    \
          uuid-dev g++ gnupg2 lsb-release

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create deps folder
        run: |
          mkdir ${{github.workspace}}/${{env.DEPS}}

      - name: Process cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/${{env.DEPS}}
          key:  ubuntu-v${{ env.CACHE_VER }}

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make
